spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    jdbc-url: jdbc:mysql://localhost:3306/bbs

mybatis:
  mapper-locations: classpath:mappers/*.xml

